services:
  db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: fsdm
      MYSQL_PASSWORD: fsdm
      MYSQL_DATABASE: auction
    ports:
      - 3307:3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: